name: Heretic-{player}

# Used to describe your yaml. Useful if you have multiple files.
description: Heretic - Random

game: Heretic
requires:
  version: 0.6.1 # Version of Archipelago required for this yaml to work as expected.

Heretic:
  # Game Options
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # 
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # 
    # **Full:** ensure everything can be reached and acquired.
    # 
    # **Minimal:** ensure what is needed to reach your goal can be acquired.
    full: 50
    minimal: 0

  goal:
    # Choose the main goal.
    # complete_all_levels: All levels of the selected episodes
    # complete_boss_levels: Boss levels (E#M8) of selected episodes
    complete_all_levels: 4
    complete_boss_levels: 1

  difficulty:
    # Choose the game difficulty. These options match Heretic's skill levels.
    # wet nurse (Thou needeth a wet-nurse) - Fewer monsters and more items than medium. Damage taken is halved, and ammo pickups carry twice as much ammo. Any Quartz Flasks and Mystic Urns are automatically used when the player nears death.
    # easy (Yellowbellies-r-us) - Fewer monsters and more items than medium.
    # medium (Bringest them oneth) - Completely balanced, this is the standard difficulty level.
    # hard (Thou art a smite-meister) - More monsters and fewer items than medium.
    # black plague (Black plague possesses thee) - Same as hard, but monsters and their projectiles move much faster. Cheating is also disabled.
    wet_nurse: 2
    easy: 4
    medium: 8
    hard: 1
    black_plague: 0

  random_monsters:
    # Choose how monsters are randomized.
    # vanilla: No randomization
    # shuffle: Monsters are shuffled within the level
    # random_balanced: Monsters are completely randomized, but balanced based on existing ratio in the level. (Small monsters vs medium vs big)
    # random_chaotic: Monsters are completely randomized, but balanced based on existing ratio in the entire game.
    vanilla: 2
    shuffle: 8
    random_balanced: 2
    random_chaotic: 1

  random_pickups:
    # Choose how pickups are randomized.
    # vanilla: No randomization
    # shuffle: Pickups are shuffled within the level
    # random_balanced: Pickups are completely randomized, but balanced based on existing ratio in the level. (Small pickups vs Big)
    vanilla: 1
    shuffle: 4
    random_balanced: 2

  random_music:
    # Level musics will be randomized.
    # vanilla: No randomization
    # shuffle_selected: Selected episodes' levels will be shuffled
    # shuffle_game: All the music will be shuffled
    vanilla: 50
    shuffle_selected: 0
    shuffle_game: 0

  allow_death_logic:
    # Some locations require a timed puzzle that can only be tried once.
    # After which, if the player failed to get it, the location cannot be checked anymore.
    # By default, no progression items are placed here. There is a way, hovewer, to still get them:
    # Get killed in the current map. The map will reset, you can now attempt the puzzle again.
    'false': 50
    'true': 0

  pro:
    # Include difficult tricks into rules. Mostly employed by speed runners.
    # i.e.: Leaps across to a locked area, trigger a switch behind a window at the right angle, etc.
    'false': 50
    'true': 0

  check_sanity:
    # Include redundant checks. This increase total check count for the game.
    # i.e.: In a room, there might be 3 checks close to each other. By default, two of them will be remove.
    # This was done to lower the total count check for Heretic, as it is quite high compared to other games.
    # Check Sanity restores original checks.
    'false': 50
    'true': 0

  start_with_map_scrolls:
    # Give the player all Map Scroll items from the start.
    'false': 0
    'true': 1

  reset_level_on_death:
    # When dying, levels are reset and monsters respawned. But inventory and checks are kept.
    # Turning this setting off is considered easy mode. Good for new players that don't know the levels well.
    'false': 0
    'true': 50

  death_link:
    # When you die, everyone who enabled death link dies. Of course, the reverse is true too.
    'false': 50
    'true': 0

  episode1:
    # City of the Damned.
    # If none of the episodes are chosen, Episode 1 will be chosen by default.
    'false': 1
    'true': 2

  episode2:
    # Hell's Maw.
    # If none of the episodes are chosen, Episode 1 will be chosen by default.
    'false': 1
    'true': 2

  episode3:
    # The Dome of D'Sparil.
    # If none of the episodes are chosen, Episode 1 will be chosen by default.
    'false': 1
    'true': 1

  episode4:
    # The Ossuary.
    # If none of the episodes are chosen, Episode 1 will be chosen by default.
    'false': 2
    'true': 1

  episode5:
    # The Stagnant Demesne.
    # If none of the episodes are chosen, Episode 1 will be chosen by default.
    'false': 2
    'true': 1

  split_bag_of_holding:
    # Split the Bag of Holding into six individual items, each one increasing ammo capacity for one type of weapon only.
    'false': 2
    'true': 1

  bag_of_holding_count:
    # How many Bags of Holding will be available.
    # If Split Bag of Holding is set, this will be the number of each capacity upgrade available.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 10
    1: 0
    random: 1
    random-low: 0
    random-high: 0

  max_ammo_crystals:
    # Set the starting ammo capacity for crystals (Elven Wand ammo).
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 100
    # Maximum value is 999
    100: 0
    random: 1
    random-low: 0
    random-high: 0

  max_ammo_arrows:
    # Set the starting ammo capacity for arrows (Ethereal Crossbow ammo).
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 50
    # Maximum value is 999
    50: 0
    random: 1
    random-low: 0
    random-high: 0

  max_ammo_claw_orbs:
    # Set the starting ammo capacity for claw orbs (Dragon Claw ammo).
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 200
    # Maximum value is 999
    200: 0
    random: 1
    random-low: 0
    random-high: 0

  max_ammo_runes:
    # Set the starting ammo capacity for runes (Hellstaff ammo).
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 200
    # Maximum value is 999
    200: 0
    random: 1
    random-low: 0
    random-high: 0

  max_ammo_flame_orbs:
    # Set the starting ammo capacity for flame orbs (Phoenix Rod ammo).
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 20
    # Maximum value is 999
    20: 0
    random: 1
    random-low: 0
    random-high: 0

  max_ammo_spheres:
    # Set the starting ammo capacity for spheres (Firemace ammo).
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 150
    # Maximum value is 999
    150: 0
    random: 1
    random-low: 0
    random-high: 0

  added_ammo_crystals:
    # Set the amount of crystal capacity gained when collecting a bag of holding or a capacity upgrade.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 10
    # Maximum value is 999
    100: 0
    random: 1
    random-low: 0
    random-high: 0

  added_ammo_arrows:
    # Set the amount of arrow capacity gained when collecting a bag of holding or a capacity upgrade.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 5
    # Maximum value is 999
    50: 0
    random: 1
    random-low: 0
    random-high: 0

  added_ammo_claw_orbs:
    # Set the amount of claw orb capacity gained when collecting a bag of holding or a capacity upgrade.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 20
    # Maximum value is 999
    200: 0
    random: 1
    random-low: 0
    random-high: 0

  added_ammo_runes:
    # Set the amount of rune capacity gained when collecting a bag of holding or a capacity upgrade.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 20
    # Maximum value is 999
    200: 0
    random: 1
    random-low: 0
    random-high: 0

  added_ammo_flame_orbs:
    # Set the amount of flame orb capacity gained when collecting a bag of holding or a capacity upgrade.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 2
    # Maximum value is 999
    20: 0
    random: 1
    random-low: 0
    random-high: 0

  added_ammo_spheres:
    # Set the amount of sphere capacity gained when collecting a bag of holding or a capacity upgrade.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 15
    # Maximum value is 999
    150: 0
    random: 1
    random-low: 0
    random-high: 0

  # Item & Location Options
  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_inventory_from_pool:
    # Start with these items and don't place them in the world.
    # 
    # The game decides what the replacement items will be.
    {}

  start_hints:
    # Start with these item's locations prefilled into the ``!hint`` command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the ``!hint`` command.
    []

  exclude_locations:
    # Prevent these locations from having an important item.
    []

  priority_locations:
    # Prevent these locations from having an unimportant item.
    []

  item_links:
    # Share part of your item pool with other players.
    []

triggers:
# if the goal is boss levels, include all episodes
- option_category: Heretic
  option_name: goal
  option_result: complete_boss_levels
  options:
    Heretic:
      episode1: true
      episode2: true
      episode3: true
      episode4: true
      episode5: true